### ISSUE TITLE
看板娘无法显示

### ISSUE THREAD

**Issue by xulei131401** [valaxyjs/valaxy-addon-live2d#1]
![微信图片_20240905140150](https://github.com/user-attachments/assets/7b257f58-bfc4-4dfc-a2f2-106bcccf257f)
![微信图片_20240905140206](https://github.com/user-attachments/assets/ed00c8a2-95d7-4849-9f52-32e7314e5462)

**Comment by WRXinYue** [comment]
删除锁文件如 `pnpm-lock.yaml` 以及 `node_modules` 后重新尝试安装

相关: https://github.com/pixijs/pixijs/wiki/Upgrading-PixiJS

**Comment by WRXinYue** [comment]
由于长时间未收到回复，该问题已经关闭。如果仍有任何疑问可以重新打开

**Comment by WRXinYue** [comment]
`pixi-live2d-display` 已升级至 [v0.5.0-beta](https://github.com/guansss/pixi-live2d-display/releases/tag/v0.5.0-beta)，应该可以避免版本冲突
